#!/bin/bash

echo "📱 AssetWorks Mobile - iPhone Installation Guide"
echo "================================================"
echo ""
echo "This app is ready to install on your iPhone!"
echo ""
echo "METHOD 1: Using Xcode (Recommended)"
echo "------------------------------------"
echo "1. Xcode should already be open with the project"
echo "2. Connect your iPhone via USB cable"
echo "3. Select your iPhone from the device dropdown (top toolbar)"
echo "4. Click the Run button (▶️) or press Cmd+R"
echo "5. If asked, enter your Mac password to allow code signing"
echo "6. The app will install and launch on your iPhone"
echo ""
echo "METHOD 2: Using Flutter Command"
echo "--------------------------------"
echo "Run this command:"
echo "flutter run --release"
echo ""
echo "Then select your iPhone from the device list"
echo ""
echo "TROUBLESHOOTING:"
echo "----------------"
echo "If you see 'Untrusted Developer' on your iPhone:"
echo "1. Go to Settings > General > Device Management"
echo "2. Tap your developer account"
echo "3. Tap 'Trust [Your Apple ID]'"
echo "4. Tap 'Trust' in the popup"
echo ""
echo "APP DETAILS:"
echo "-------------"
echo "Name: AssetWorks Mobile"
echo "Bundle ID: com.assetworks.assetworksMobileNew"
echo "Version: 1.0.0"
echo "Build: Release"
echo ""
echo "Press Enter to open Xcode with the project..."
read

open -a Xcode /Users/Victor/Projects/assetworks_mobile_new/ios/Runner.xcworkspace